from django.urls import path
from CarRental import views


urlpatterns = [
    path('own_register/', views.Owner_Register, name='Owner_Register'),
    path('mem_register/', views.Member_Register, name='Member_Register'),
    path('sign_in/', views.userSignin, name='signIn'),
    path('logout/', views.userLogout, name='logout'),
    path('memberEdit/',views.memberedit,name='memberedit'),
    path('backend/', views.backend_index, name='backend_index'),
    path('backend/car_type/<pageNo>', views.backend_Cartype, name='backend_Cartype'),
    path('backend/car/<pageNo>', views.backend_Car, name='backend_Car'),
    path('backend/car_add', views.backend_Car_add, name='backend_Car_add'),
    path('backend/car_edit/<car_id>', views.backend_Car_edit, name='backend_Car_edit'),
    path('backend/car_delete/<car_id>', views.backend_Car_delete, name='backend_Car_delete'),
    path('backend/type_add', views.backend_Type_add, name='backend_Type_add'),
    path('backend/type_edit/<type_id>', views.backend_Type_edit, name='backend_Type_edit'),
    path('backend/type_delete/<type_id>', views.backend_Type_delete, name='backend_Type_delete'),
    path('backend/bank/<pageNo>', views.backend_Bank, name='backend_Bank'),
    path('backend/bank_add', views.bankOwn_add, name='bankOwn_add'),
    path('backend/bank_edit/<id>', views.backend_Bank_edit, name='backend_Bank_edit'),
    path('backend/bank_dalete/<id>', views.backend_Bank_delete, name='backend_Bank_delete'),
    path('backend/rent/<pageNo>', views.backend_Rent, name='backend_Rent'),
    path('backend/rentHistory/<pageNo>', views.backend_RentHistory, name='backend_RentHistory'),
    path('backend/rentHistoryDetail/<rent_id>', views.backend_RentHistoryDetails, name='backend_RentHistoryDetails'),
    path('backend/rentDetail/<rent_id>', views.backend_RentDetails, name='backend_RentDetails'),
    path('backend/rentConfirm/<rent_id>/<car_id>', views.rentConfirm, name='rent_Confirm'),
    path('backend/reject/<rent_id>/<car_id>/', views.rentReject, name='rentReject'),
    path('backend/accepts/<rent_id>/', views.backend_Accepts, name='backend_Accepts'),
    path('backend/incompleteTransfer/<rent_id>/', views.incompleteTransfer, name='incompleteTransfer'),
    path('backend/rentSuccess/<rent_id>/<car_id>', views.rentSuccess, name='rentSuccess'),
    path('backend/roportQD', views.reportQD, name='reportQD'),
    path('backend/roportQM', views.reportQM, name='reportQM'),
    path('backend/roportQY', views.reportQY, name='reportQY'),
    path('pdfReceipt/<rent_id>', views.pdfReceipt, name='pdfReceipt'),
    path('backend/address',views.backend_address,name='address'),
    path('backend/address_add',views.backend_address_add,name='address_add'),
    path('backend/address_edit/<id>',views.backend_address_edit,name='address_edit'),
    path('backend/address_delete/<id>',views.backend_Address_delete,name='address_delete'),
    path('backend/Memberlist/<pageNo>',views.Memberlist,name='Memberlist'),
    path('backend/Member_add',views.Member_add,name='Member_add'),

    path('memChangePassword/',views.memChangePassword,name='memChangePassword'),
    path('showCarAll/',views.showCarAll,name='showCarAll'),
    path('carDetail/<car_id>',views.carRentDetail,name='carDetail'),
    path('memrent/<rent_id>',views.memRent,name='memRent'),
    path('memRentList/<pageNo>',views.memRentList,name='memRentList'),
    path('cancel/<rent_id>/<car_id>',views.rentCancel,name='rentCancel'),
    path('memPayment/<rent_id>',views.memPayment,name='memPayment'),

    ]