# Generated by Django 4.1.2 on 2023-02-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('location', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(default='', upload_to='static/image/Bank/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=20)),
                ('car_model', models.CharField(default='', max_length=30)),
                ('gearType', models.CharField(default='', max_length=30)),
                ('seat', models.CharField(default='', max_length=30)),
                ('img', models.ImageField(default='', upload_to='static/image/cars/')),
                ('price', models.FloatField(default=0.0)),
                ('status', models.IntegerField(default=0)),
                ('desc', models.CharField(default='', max_length=800)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.adress')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('type_id', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=20, unique=True)),
                ('picture', models.ImageField(default='', upload_to='static/image/types/')),
            ],
        ),
        migrations.CreateModel(
            name='Geographies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=50)),
                ('tel', models.CharField(default='', max_length=10)),
                ('img', models.ImageField(default='', upload_to='static/image/Member/')),
            ],
        ),
        migrations.CreateModel(
            name='OwnBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_num', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=30)),
                ('branch', models.CharField(default='', max_length=30)),
                ('bank_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('own_id', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('tel', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=35)),
                ('linkLocation', models.URLField(default='')),
                ('birthdate', models.DateField(blank=True, default='', null=True)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='static/image/Owner/')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('rent_date', models.DateField(blank=True, default='', null=True)),
                ('return_date', models.DateField(blank=True, default='', null=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='', max_length=3)),
                ('price', models.FloatField(default=0.0)),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.car')),
                ('mem_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.member')),
                ('own_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_date', models.DateTimeField(auto_now_add=True)),
                ('pay_num', models.CharField(default='', max_length=35)),
                ('slip', models.ImageField(default='', upload_to='static/bills/')),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.ownbank')),
                ('rent_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.rent')),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('own', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.owner')),
                ('rent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.rent')),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=30)),
                ('name_th', models.CharField(default='', max_length=30)),
                ('name_en', models.CharField(default='', max_length=30)),
                ('geography_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.geographies')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(default='', max_length=13)),
                ('pay_total', models.FloatField(default=0.0)),
                ('pay_date', models.DateField(blank=True, default='', null=True)),
                ('slip_img', models.ImageField(default='', upload_to='static/image/Slip/')),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.ownbank')),
                ('rent_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.rent')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='provinces',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.provinces'),
        ),
        migrations.AddField(
            model_name='ownbank',
            name='own_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.owner'),
        ),
        migrations.AddField(
            model_name='member',
            name='provinces',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.provinces'),
        ),
        migrations.CreateModel(
            name='Confirms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('own', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.owner')),
                ('rent_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.rent')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='own_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.owner'),
        ),
        migrations.AddField(
            model_name='car',
            name='provinces',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.provinces'),
        ),
        migrations.AddField(
            model_name='car',
            name='type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.cartype'),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('mem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.member')),
                ('rent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.rent')),
            ],
        ),
        migrations.AddField(
            model_name='adress',
            name='own_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.owner'),
        ),
        migrations.AddField(
            model_name='adress',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.provinces'),
        ),
        migrations.CreateModel(
            name='Accepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('own', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.owner')),
                ('rent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CarRental.rent')),
            ],
        ),
    ]
